[project]
name = "piv-estudo-python"
version = "0.1.0"
description = "PIV Estudo - Python Module"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "gdown>=5.2.0",
    "landingai>=0.3.48",
]
